### PR TITLE
fix: add `miner_id` to `retrievable_deals` PK

### PR DESCRIPTION
**Pull request by bajtos**
Before this change, we used `cid` as the primary key. As a result, we would have only one record for each CID.

### CODE REVIEW

**Comment by bajtos** [comment]
I discovered this problem while troubleshooting https://filecoinproject.slack.com/archives/C075188L1R9

**Review by juliangruber — CHANGES_REQUESTED** [review]
Very important fix 🙏 Could we please secure this through a regression test?

**Comment by bajtos** [comment]
> Very important fix 🙏 Could we please secure this through a regression test?

Great idea! 💪🏻

**Comment by bajtos** [comment]
Test added in [4dc65d1](https://github.com/filecoin-station/spark-api/pull/319/commits/4dc65d1090e7d87a70981ef2fda78f9eb1aad743)

@juliangruber LGTY now?

**Review by juliangruber — APPROVED** [review]
👏

**Pull request merged**
